version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm run dev

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: npm start
    depends_on:
      - postgres

  ai-risk:
    build: ./ai-services/risk_model
    ports:
      - "8001:8001"
    volumes:
      - ./ai-services/risk_model:/app
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8001

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: reinsurance
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
